CREATE TABLE shirtspec_customers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    store_id INTEGER REFERENCES shirtspec_stores(id),
    customer_name TEXT NOT NULL,
    date_modified TIMESTAMP DEFAULT now() NOT NULL,
    chest INTEGER NOT NULL,
    shirt_waist INTEGER NOT NULL,
    yoke DECIMAL(4,2),
    shaping INTEGER NOT NULL,
    left_sleeve DECIMAL(4,2),
    right_sleeve DECIMAL(4,2),
    left_cuff DECIMAL(4,2),
    right_cuff DECIMAL(4,2),
    tail INTEGER NOT NULL,
    collar DECIMAL(4,2)
);

CREATE TYPE shoulder_line AS ENUM (
    'regular',
    'square',
    'slope',
    'exteme-slope'
);

ALTER TABLE shirtspec_customers ADD COLUMN shoulder_line shoulder_line;